server:
  port: 8080

spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DEV.DB.URL}
    username: ${DEV.DB.USERNAME}
    password: ${DEV.DB.PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    open-in-view: false

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: DEBUG  # SQL 실행 로그를 DEBUG 레벨로 출력
    org.hibernate.orm.jdbc.bind: trace

discodeit:
  storage:
    type: local
    local:
      root-path: C:/storage/binaryContent
