spring:
  application:
    name: discodeit

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true #SQL을 가독성 있게 출력
          highlight_sql: true #SQL 하이라이트

  logging:
    level:
      org.hibernate.SQL: DEBUG  # SQL 실행 로그를 DEBUG 레벨로 출력
      org.springframework.context: DEBUG
      com.zaxxer.hikari: DEBUG

discodeit:
  storage:
    type: local
    local:
      root-path: C:/storage/binaryContent
