server:
  port: 8080

spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: dev

  datasource:
    url: ${DEV.DB.URL}
    username: ${DEV.DB.USERNAME}
    password: ${DEV.DB.PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: true

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hibernate.SQL: debug  # SQL 실행 로그를 DEBUG 레벨로 출력
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include:
          - "health"
          - "info" # Actuator의 info 엔드포인트 활성화
          - "metrics" # 수치지표
          - "loggers"

info:
  app:
    name: discodeit
    version: 17.0
  java:
    version: 17.0
  spring-boot:
    version: 3.4.0
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  storage:
    type: local
    path: C:/storage/binaryContent
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
