server:
  port: 80

spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: prod

  datasource:
    url: ${PROD.DB.URL}
    username: ${PROD.DB.USERNAME}
    password: ${PROD.DB.PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.SQL: info
